trigger:
  - main

schedules:
- cron: "0 */12 * * * "
  displayName: Build every 12 hours
  branches:
    include:
    - main
  always: true

variables:
- group: skill-az-function

resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/tags/V1.0
      name: pipeline-templates

extends:
  template: templates\c_sharp\template.yml@templates
  parameters:
    deploy_application: true
    run_mutations: false