services:     
     az-function-skill:
        image: az-function-skill
        container_name: az-function-skill
        build:
            context: ./src/
            dockerfile: Dockerfile
        ports:
          - "7071:80"
